name: Build and SAST

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.11-eclipse-temurin-21

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: mvn clean package
